name: Java Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Create output directory
      run: mkdir -p out

    - name: Compile Java files
      run: |
        javac -d out \
          src/main/java/com/gp27/amis/App.java \
          src/main/java/com/gp27/amis/utils/Helper.java

    - name: Copy resources
      run: cp src/main/resources/*.properties out/

    - name: Run application (test)
      run: java -cp out com.gp27.amis.App